// Generated by CoffeeScript 1.10.0
(function() {
  var $content, n, name, numbers, obj1, obj2, print, ref, ref1, ref2, ref3, section, title;

  $content = $('#content');

  section = function(title) {
    return $('<h4>').text(title).appendTo($content);
  };

  print = function(text) {
    return $('<p>').text(text).appendTo($content);
  };

  section('String interpolation');

  name = 'Dr Groot';

  title = 'plant matter expert';

  print("You know, " + name + " is our resident " + title + ".");

  section('Comprehensions');

  numbers = [1, 3, 5, 6, 7, 8, 9, 11, 12, 14, 16, 17];

  print([
    (function() {
      var i, len, results;
      results = [];
      for (i = 0, len = numbers.length; i < len; i++) {
        n = numbers[i];
        if (n > 10) {
          results.push(n * 2 + 1);
        }
      }
      return results;
    })()
  ]);

  section('Existential operator');

  obj1 = {
    artist: {
      name: 'Marty',
      latestAlbum: {
        title: 'Back in Time'
      }
    }
  };

  print((ref = obj1.artist) != null ? (ref1 = ref.latestAlbum) != null ? ref1.title : void 0 : void 0);

  obj2 = {
    artist: {
      name: 'Marty',
      latestAlbum: null
    }
  };

  print((ref2 = obj2.artist) != null ? (ref3 = ref2.latestAlbum) != null ? ref3.title : void 0 : void 0);

}).call(this);
